name: test
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/test.yml"
jobs:
  test:
    name: "Test: deadcode"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test deadcode
        uses: ./
